# -*- coding: utf-8 -*-
"""07_Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U-sPSa7BDBR7Co9WwAqcZ-Xr4qnVPuLd

#  Introduction to Python

##***Welcome to your first iPython Notebook.***

![python](https://cognitiveclass.ai/wp-content/uploads/2016/10/Machine-Learning-with-Python.png)

## **About iPython Notebooks**

iPython Notebooks are interactive coding environments embedded in a webpage. You will be using iPython notebooks in this class. You only need to write code between the ### START CODE HERE ### and ### END CODE HERE ### comments. After writing your code, you can run the cell by either pressing "SHIFT"+"ENTER" or by clicking on "Run Cell" (denoted by a play symbol) in the left bar of the cell.


**In this notebook you will learn -**


* Basic Syntax
* Variables
* Numbers
* Casting
* String

##Miscellaneous exercise

1.   Create a function that multiplies any number x by 13


*   x=14
*   if result is greater than 130 print "x is greater than 10"
*   else print "x is less than 10"
"""

### START CODE HERE ### 



### END CODE HERE ###

"""2.   Create a class called student



*   use the init() function to assign values for name and BirthYear, where name="vinay" and BirthYear="1998"
*   Create a function to find the age
"""

### START CODE HERE ### 



### END CODE HERE ###

"""3. Write a Python program which accepts the radius of a circle from the user and compute the area."""

### START CODE HERE ### 



### END CODE HERE ###

