# -*- coding: utf-8 -*-
"""Copy of 06-Operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MH6DVGeaEDA7A7tXJwvNa68vFVIaXeab

# Introduction to Pandas

![alt text](http://i1.wp.com/blog.adeel.io/wp-content/uploads/2016/11/pandas1.png?zoom=1.25&fit=818%2C163)

Pandas is an open-source, BSD-licensed Python library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. You can think of pandas as an extremely powerful version of Excel, with a lot more features.

## **About iPython Notebooks**

iPython Notebooks are interactive coding environments embedded in a webpage. You will be using iPython notebooks in this class. You only need to write code between the ### START CODE HERE ### and ### END CODE HERE ### comments. After writing your code, you can run the cell by either pressing "SHIFT"+"ENTER" or by clicking on "Run Cell" (denoted by a play symbol) in the left bar of the cell.

**In this notebook you will learn -**

* Series
* DataFrames
* Missing Data
* GroupBy
* Merging, Joining and Concatenating
* Operations
* Data Input and Output

## Importing Pandas
To import Pandas simply write the following:
"""

import pandas as pd

"""# Operations

There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category. Let's show them here in this topic:
"""

df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

"""### Info on Unique Values"""

df['col2'].unique()      #gives unique non repeated values

df['col2'].nunique()      #gives number of unique values

df['col2'].value_counts()

"""### Selecting Data"""

#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]

newdf

"""**Exercise 6.1:**

Frome the given Dataframe **df** create new Dataframe **ndf** with **col1** greater than 3 and **col2** = 444
"""

df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

### START CODE HERE ### 

### END CODE HERE ###

"""### Applying Functions"""

def times2(x):
    return x*2

df['col1'].apply(times2)

df['col3'].apply(len)

df['col1'].sum()

"""**Exercise 6.2**

Create a function **add** to add 5 to **col1** and apply it using **apply()** function.
"""

### START CODE HERE ### 
def add(x):
  return x + 5
  
df['col1'].apply(add)
### END CODE HERE ###

"""** Permanently Removing a Column:**"""

del df['col1']

df

"""** Get column and index names: **"""

df.columns

df.index

"""** Sorting and Ordering a DataFrame:**"""

df

df.sort_values(by='col2') #inplace=False by default

"""** Find Null Values or Check for Null Values:**"""

df.isnull()

# Drop rows with NaN Values
df.dropna()

"""** Filling in NaN values with something else: **"""

import numpy as np

df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

df.fillna('FILL')

data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

df

df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

"""# New Section

**Excercise**

1. How to create a Pandas DataFrame?
"""

### START CODE HERE ### 

### END CODE HERE ###

"""2. How to Select an Index or Column From a Pandas DataFrame.?

Now, let’s say you have a DataFrame like this one:

   A  B  C
   
0  1  2  3

1  4  5  6

2  7  8  9

And you want to access the value that is at index 0, in column ‘A’.
"""

### START CODE HERE ### 

### END CODE HERE ###

"""3. How to select rows and columns in DataFrame.?

Now, let’s say you have a DataFrame like this one:

A B C

0 1 2 3

1 4 5 6

2 7 8 9
"""

### START CODE HERE ### 

### END CODE HERE ###

"""4.  How To Add an Index to a DataFrame.?

you can easily do this by calling set_index() on your DataFrame.

Now, let’s say you have a DataFrame like this one:

A B C

0 1 2 3

1 4 5 6

2 7 8 9
"""

### START CODE HERE ### 

### END CODE HERE ###

"""5. How to add rows to a DataFrame.?

.loc[] works on labels of your index. 

.iloc[] works on the positions in your index. 

.ix[] is a more complex case: when the index is integer-based, you pass a label to .ix[]

Now, let’s say you have a DataFrame like this one:

A B C

0 1 2 3

1 4 5 6

2 7 8 9
"""

### START CODE HERE ### 

### END CODE HERE ###

"""6. check the  difference between .iloc[], .loc[] and .ix[]"""

### START CODE HERE ### 

### END CODE HERE ###

"""7. How to append columns to DataFrame.?"""

### START CODE HERE ### 

### END CODE HERE ###

"""8. How to reset index of DataFrame.?

it can be done using .reset_index().
"""

### START CODE HERE ### 

### END CODE HERE ###

"""9. How to Delete Index from a Pandas DataFrame.?"""

### START CODE HERE ### 

### END CODE HERE ###

"""10. How to delete column from a Pandas DataFrame.?"""

### START CODE HERE ### 

### END CODE HERE ###

"""11. How to delete rows from a Pandas DataFrame.?"""

### START CODE HERE ### 

### END CODE HERE ###

"""12. How to Rename the Index or Columns of a Pandas DataFrame.?"""

### START CODE HERE ### 

### END CODE HERE ###

"""13. How replace all occurences of a string in a DataFrame.?"""

### START CODE HERE ### 

### END CODE HERE ###

"""14. Removing Parts From Strings in the Cells of Your DataFrame"""

### START CODE HERE ### 

### END CODE HERE ###

"""15.  How To Create an Empty DataFrame.?"""

### START CODE HERE ### 

### END CODE HERE ###

"""16. How To Iterate Over a Pandas DataFrame.?

You can iterate over the rows of your DataFrame with the help of a for loop in combination with an iterrows() call on your DataFrame:

iterrows() allows you to efficiently loop over your DataFrame rows as (index, Series) pairs. In other words, it gives you (index, row) tuples as a result.
"""

### START CODE HERE ### 

### END CODE HERE ###

"""17. Create an Empty DataFrame"""

### START CODE HERE ### 

### END CODE HERE ###

"""18. Create a DataFrame from Lists"""

### START CODE HERE ### 

### END CODE HERE ###

"""19. Create a DataFrame from list of lists"""

### START CODE HERE ### 

### END CODE HERE ###

"""20. Create a DataFrame from Dict of ndarrays / Lists"""

### START CODE HERE ### 

### END CODE HERE ###

"""21.  create an indexed DataFrame using arrays."""

### START CODE HERE ### 

### END CODE HERE ###

"""22. create a DataFrame by passing a list of dictionaries."""

### START CODE HERE ### 

### END CODE HERE ###

"""23.  how to create a DataFrame by passing a list of dictionaries and the row indices..?"""

### START CODE HERE ### 

### END CODE HERE ###

"""24. how to create a DataFrame with a list of dictionaries, row indices, and column indices."""

### START CODE HERE ### 

### END CODE HERE ###

"""25. Add new rows to a DataFrame using the append function."""

### START CODE HERE ### 

### END CODE HERE ###

"""[For Solutions Click Here!](https://drive.google.com/open?id=1NcPwIEZCJNBMJC-KJBg2WvVImQ9JaSn0)"""