# -*- coding: utf-8 -*-
"""Solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18415woXBtzlbKgvmsidqhKRWd6qolrF4

**Exercise** 1.1
"""

print("Batman is the best superhero")

"""**Exercise** 1.2"""

x = 10
y = "Hello there"
print(x)
print(y)

"""**Exercise** 1.3"""

x = 5
y = 15
z = x + y                          
print(z)

"""**Exercise** 1.4"""

print(type(E))

"""**Exercise** 1.5"""

x = 3
y = "4"
z = x + int(y)
print(Z)

"""**Exercise** 1.6"""

x = str[0]
print(x)

"""**Exercise** 1.7"""

x = str[3:8]                                  
print(x)thod

"""**Exercise** 1.8"""

E=E.lower()                     #lowercase
print(E)                        
print(E.replace("s","d"))       #replace s by d
print(len(E))                   #length of the string

"""**Exercise** 2.1"""

x = 50
y = 49
if x > y:
  print("Joker")

"""**Exercise** 2.2"""

num = -6
if num > 0:
 print(num, "is a positive number.")
else:
 print(num, "is a negative number.")

"""**Exercise** 2.3"""

i = 1

while i < 3:
 print("yo")
 i += 1

"""**Exercise** 2.4"""

for x in range(11):
 if(x%2==0):
  print(x)

"""**Exercise** 3.1"""

BestOfTv = ["Breaking Bad", "Game Of Thrones", "Mr Robot"]
print(BestOfTv)
BestOfTv.pop(1)
print(BestOfTv)
BestOfTv.insert(0,"Friends")
print(BestOfTv)
if "Game Of Thrones" in BestOfTv:
  print("GOT is in BestOfTv")
else:
  print("GOT is not in BestOfTv")

"""**Exercise** 3.2"""

food = ("pizaa", "burger", "cake") 
print(len(thistuple))
print(food[2])

"""**Exercise** 3.3"""

games = {"witcher", "cs", "fortnite"}
print(games)
games.add("pubg")
print(games)
games.remove("fortnite")
print(games)
games.clear()
print(games)

"""**Exercise** 3.4"""

d = {0:10, 1:20}
print(d)
d.update({2:30})
print(d)

"""**Exercise** 4.1"""

def display():
  print("Hello from a function")

"""**Exercise** 4.2"""

def my_function(x):
  return(x-10)

"""**Exercise** 4.3"""

def add(x,y):
  return(x+y)
print(add(12,36))

"""**Exercise** 4.4"""

def shut_down(s):
  if(s==1):
    return "Shutting down"
  elif(s==2):
    return "Shutdown Aborted"
  else:
    return "Sorry"

"""**Exercise** 4.5"""

def add(x,y):
  return(x+y)

def subtract(x,y):
  return(x-y)

def divide(x,y):
  return(x/y)

def multiply(x,y):
  return(int(x*y))

print(add(8,4))
print(subtract(8,4))
print(divide(8,4))
print(multiply(8,4))

"""**Exercise **4.6"""

def greet(*names):                                                     ## This function greets all the person in the names tuple
   for name in names:
    print("Hello",name)
    
greet("Monica","Ross","Chandler","Joey","Rachel","Phoebe")              ## function call

"""**Exercise **4.6"""

